# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170320_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_title',
        ),
        migrations.AddField(
            model_name='song',
            name='documnet_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='song',
            name='documnet_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
