# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170321_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='documnet_title',
            new_name='document_title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='documnet_url',
            new_name='document_url',
        ),
    ]
