# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_meditator'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditator',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meditator',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
