# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_info', '0003_document_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
