# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_info', '0004_document_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
